// flow-typed signature: cd8172f58203f6b434b8d230f1010b0f
// flow-typed version: <<STUB>>/@nivo/radar_v^0.50.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nivo/radar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nivo/radar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@nivo/radar/cjs/nivo-radar' {
  declare module.exports: any;
}

declare module '@nivo/radar/umd/nivo-radar' {
  declare module.exports: any;
}

// Filename aliases
declare module '@nivo/radar/cjs/nivo-radar.js' {
  declare module.exports: $Exports<'@nivo/radar/cjs/nivo-radar'>;
}
declare module '@nivo/radar/index' {
  declare module.exports: $Exports<'@nivo/radar'>;
}
declare module '@nivo/radar/index.js' {
  declare module.exports: $Exports<'@nivo/radar'>;
}
declare module '@nivo/radar/umd/nivo-radar.js' {
  declare module.exports: $Exports<'@nivo/radar/umd/nivo-radar'>;
}
